### ISSUE TITLE
Can't install on Windows due to error in ReadMe.md via setup.py

### ISSUE THREAD

**Issue by RaddishIoW** [franklintiel/django2-semantic-ui#2]
There seems to be an error in the ReadMe.md file when read by the setup.py file on installing from pip:
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\adam\AppData\Local\Temp\pip-install-t09tbnoe\django2-semantic-ui\setup.py", line 5, in <module>
        long_description = fh.read()
      File "c:\users\adam\envs\hayl\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 919: character maps to undefined
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\adam\AppData\Local\Temp\pip-install-t09tbnoe\django2-semantic-ui\

**Comment by franklintiel** [comment]
Hi my friend, I will working on fix this issue, thanks for you reply!
